/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_surina_soundtouch_SoundTouch */

#ifndef _Included_net_surina_soundtouch_SoundTouch
#define _Included_net_surina_soundtouch_SoundTouch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_surina_soundtouch_SoundTouch
 * Method:    getVersionString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_surina_soundtouch_SoundTouch_getVersionString
  (JNIEnv *, jclass);

/*
 * Class:     net_surina_soundtouch_SoundTouch
 * Method:    setTempo
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_net_surina_soundtouch_SoundTouch_setTempo
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     net_surina_soundtouch_SoundTouch
 * Method:    setSampleRate
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_surina_soundtouch_SoundTouch_setSampleRate
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_surina_soundtouch_SoundTouch
 * Method:    setChannels
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_surina_soundtouch_SoundTouch_setChannels
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_surina_soundtouch_SoundTouch
 * Method:    putSample
 * Signature: ([S)V
 */
JNIEXPORT void JNICALL Java_net_surina_soundtouch_SoundTouch_putSample
  (JNIEnv *, jclass, jshortArray);

/*
 * Class:     net_surina_soundtouch_SoundTouch
 * Method:    receiveSample
 * Signature: (I)[S
 */
JNIEXPORT jshortArray JNICALL Java_net_surina_soundtouch_SoundTouch_receiveSample
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_surina_soundtouch_SoundTouch
 * Method:    stretch
 * Signature: (Ljava/lang/String;Ljava/lang/String;IIIZ)V
 */
JNIEXPORT void JNICALL Java_net_surina_soundtouch_SoundTouch_stretch
  (JNIEnv *, jclass, jstring, jstring, jint, jint, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
